### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by vmr1532**
Created a CODE_OF_CONDUCT.md file for making the contributors to understand the code of conduct in the commerce.js community.

### CODE REVIEW

**Comment by robbieaverill** [comment]
Hi @vmr1532, where did you copy this from?

**Comment by pushparavi123** [comment]
I just typed it myself.

**Comment by vmr1532** [comment]
I just referred few docs and typed this and created it myself.

**Comment by robbieaverill** [comment]
Thank you for your contribution, I think we'd prefer to write our own expectations for our contributors rather than use a generic template. Have a nice week!

**Pull request closed without merging**
