### PR TITLE
Fix window is not defined error by using typeof

### PR DESCRIPTION
**Pull request by PaitoAnderson**

### CODE REVIEW

**Review by ScopeyNZ — APPROVED** [review]

**Comment by ScopeyNZ** [comment]
Will set a reminder to do a bugfix release on Monday.

**Comment by lakhansamani** [comment]
@PaitoAnderson thanks for the fix, waiting for this release to happen!

**Comment by ScopeyNZ** [comment]
Released in 2.7.1

**Comment by lakhansamani** [comment]
Thanks  @ScopeyNZ

**Pull request merged**
